[[redirects]]
    from = "/home"
    to = "/home"
    status = 200

[[redirects]]
    from = "/projects"
    to = "/projects"
    status = 200

[[redirects]]
    from = "/knowledges"
    to = "/knowledges"
    status = 200

[[redirects]]
    from = "/experience"
    to = "/experience"
    status = 200

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200