[build]
    command = "npm run build"
    publish = "/build"
    base = "/"

[[redirects]]
    from = "/home"
    to = "/home"
    status = 200

[[redirects]]
    from = "/projects"
    to = "/projects"
    status = 200

[[redirects]]
    from = "/knowledges"
    to = "/knowledges"
    status = 200

[[redirects]]
    from = "/experience"
    to = "/experience"
    status = 200

[[redirects]]
    from = "/*"
    to = "/"
    status = 200